#define BUFFER_SIZE 1000
#define MAXIMUM_CONNECTIONS 5
#define CONFIG_PATH "/.evenscriberc"
#define SOCKET_PATH "/tmp/olympus_socket.sock"
#define TABLE_NAME "logs"
#define CONN_THREADS 2
#define READ_THREADS 4
#define WRITE_THREADS 4
#define SAVE_THRESHOLD 1000
